### ISSUE TITLE
Creating new VCR specs?

### ISSUE THREAD

**Issue by ideasasylum** [shimoju/metabase-ruby#51]
I was working on adding new endpoint support (/dashboard/:id) and noticed all the specs use webmock and vcr. This seems to assume a Metabase instance running locally—I was wondering if the Metabase database could be included in the gem so these VCR cassettes are easier to regenerate?

**Comment by shimoju** [comment]
Sorry for the delay. Nice idea! I added Metabase DB in repository and regenerate vcr_cassettes 
 #63. How is this?
